# Generated by Django 3.1.4 on 2022-03-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('이름', models.CharField(max_length=20)),
                ('나이', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('작업장', models.CharField(max_length=30)),
                ('주소', models.CharField(max_length=300)),
                ('관리자', models.CharField(max_length=20)),
            ],
        ),
    ]
